#运行环境的启动方法 zookeeper
version: '3'
services:
  mongodb:
    image: mongo:4.4.17
    container_name: "mongodb"
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123456
    networks:
      - mongo_net
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: "mongo-express"
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root123456
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root123456
    networks:
      - mongo_net
    depends_on:
      - mongodb
networks:
  mongo_net:
    driver: bridge